const fs=require('fs'),cheerio=require('cheerio'),c=require('../data/catalog.json'),english=require('../data/catalog-en.json');
for(const lang of ['es','en']){const prefix=lang==='en'?'en/':'',en=lang==='en';
for(const page of ['kitesurf.html','experiences.html']){const f=prefix+page,$=cheerio.load(fs.readFileSync(f,'utf8'));
if(page==='kitesurf.html'&&!$('[onclick*="kitesurf_medio"]').length){const card=$('[onclick*="kitesurf_iniciacion"]').first().closest('[data-category]').clone();card.find('h3').text(en?'Intermediate Course (4 hours)':'Curso Medio (4 horas)');card.find('p').first().text(en?'Four hours of guided training to develop your kite skills. Equipment and hydration included.':'Cuatro horas de entrenamiento guiado para desarrollar tu técnica de kite. Equipo e hidratación incluidos.');card.find('span.rounded-full').first().text(en?'4 hours':'4 horas');card.find('[onclick*="addToCart"]').attr('onclick',"addToCart('kitesurf_medio', this)");card.find('[onclick*="openWhatsApp"]').attr('onclick',"openWhatsApp('"+(en?'I would like information about the 4-hour kite course.':'Quiero información del curso medio de kite de 4 horas.')+"')");card.attr('data-order','2.5');$('#kitesurf-grid').append(card);}
$('#kitesurf-grid>[data-category]').each((i,e)=>{const card=$(e),id=(card.find('[onclick*="addToCart"]').attr('onclick')||'').match(/addToCart\(['"]([^'"]+)/)?.[1],p=c.products[id];if(!p)return;card.attr('data-price',p.price);card.find('.price-value').attr('data-product-id',id).attr('data-cop-val',p.price).text('$'+p.price.toLocaleString('es-CO')+' COP');if(card.attr('data-category')==='curso'&&!card.find('.hydration-note').length)card.find('p').first().after('<p class="hydration-note text-sm mb-3">'+(en?'Hydration included.':'Hidratación incluida.')+'</p>');});
$('option[value^="kitesurf_"]').each((i,e)=>{const p=c.products[$(e).attr('value')];if(p)$(e).attr('data-price',p.price).text((en?english[$(e).attr('value')][0]:p.name)+' — $'+p.price.toLocaleString('es-CO')+' COP');});
if($('#kite-course-select').length&&!$('option[value=kitesurf_medio]').length)$('#kite-course-select').append('<option value="kitesurf_medio" data-price="1310000" data-unit="persona">'+(en?'Intermediate Course (4 hours)':'Curso Medio (4 horas)')+' — $1.310.000 COP</option>');
$('script[type="application/ld+json"]').each((i,e)=>{let d;try{d=JSON.parse($(e).html())}catch{return}const lists=(d['@graph']||[]).filter(n=>n['@type']==='ItemList');if(page==='kitesurf.html')for(const list of lists){list.itemListElement=Object.entries(c.products).filter(([id])=>id.startsWith('kitesurf_')).map(([id,p],i)=>({'@type':'ListItem',position:i+1,item:{'@type':'TouristTrip',name:en?english[id][0]:p.name,offers:{'@type':'Offer',price:p.price,priceCurrency:'COP',url:'https://dunasyolas.com/'+prefix+'kitesurf'}}}));list.numberOfItems=list.itemListElement.length;}$(e).text(JSON.stringify(d));});
 $('#kite-total-preview').text('$650.000 COP');$('#kite-course-select').closest('[data-category]').attr('data-price',650000);
 $('script[src*="catalog.js"]').attr('src','/js/catalog.js?v=20260915prices');fs.writeFileSync(f,$.html());}}
