/* Edit data/catalog.json and data/catalog-en.json; this file generates the browser catalog. */
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
function writeFileWithRetry(file, contents) {
  for (let attempt = 0; attempt < 8; attempt += 1) {
    try { fs.writeFileSync(file, contents); return; }
    catch (error) {
      if (!['UNKNOWN', 'EBUSY', 'EPERM'].includes(error.code) || attempt === 7) throw error;
      Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 100 * (attempt + 1));
    }
  }
}
const catalog = JSON.parse(fs.readFileSync(path.join(root, 'data/catalog.json'), 'utf8'));
const english = JSON.parse(fs.readFileSync(path.join(root, 'data/catalog-en.json'), 'utf8'));
for (const [id, product] of Object.entries(catalog.products)) {
  if (!Number.isFinite(product.price) || product.price < 0) throw new Error(`Invalid price: ${id}`);
  if (!english[id]) throw new Error(`Missing English catalog entry: ${id}`);
  product.nameEn = english[id][0]; product.descriptionEn = english[id][1];
}
const data = JSON.stringify(catalog).replace(/</g, '\\u003c');
fs.writeFileSync(path.join(root, 'js/catalog.js'), `/* Generated by scripts/build-catalog.js. */
(function () {
  var data = ${data};
  var en = document.documentElement.lang.indexOf('en') === 0;
  var units = {persona:'person',clase:'lesson',hora:'hour',sesión:'session',grupo:'group',día:'day',bote:'boat',servicio:'service',tabla:'board'};
  var activities = {};
  Object.keys(data.products).forEach(function(id) {
    var p = data.products[id];
    if (en) { p.name = p.nameEn; p.description = p.descriptionEn; p.unit = units[p.unit] || p.unit; }
    if (p.planner) {
      activities[p.plannerId || id] = Object.assign({},p.planner,{name:p.name,description:p.description,price:p.price,priceUSD:p.priceUSD,image:p.image,link:p.route ? (en?'/en':'')+p.route : null,productId:id});
      if(en) activities[p.plannerId || id].duration = (p.planner.duration||'').replace('Todo el día','Full day').replace('Día completo','Full day').replace('Medio día','Half day').replace('minutos','minutes').replace('horas','hours').replace('hora','hour').replace('Día y noche','Day and evening');
    }
  });
  window.DYO_CATALOG = {products:data.products,activities:activities,packages:data.packages};
})();\n`);
console.log(`Catalog: ${Object.keys(catalog.products).length} products; ${Object.values(catalog.products).filter(p=>p.planner).length} planner activities.`);

const cheerio = require('cheerio');
function walk(dir) { return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>['node_modules','.git','tmp'].includes(e.name)?[]:e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]); }
for (const f of walk(root).filter(f=>f.endsWith('.html'))) {
 const $=cheerio.load(fs.readFileSync(f,'utf8'));const en=$('html').attr('lang')==='en';
 $('[data-product-id]').each((i,e)=>{const p=catalog.products[$(e).attr('data-product-id')];if(!p)return;$(e).attr('data-cop-val',p.price).text('$'+p.price.toLocaleString(en?'en-US':'es-CO')+' COP');});
 $('[data-package-price]').each((i,e)=>{const pkg=catalog.packages[$(e).attr('data-package-price')];if(!pkg)return;const total=pkg.activities.reduce((n,id)=>n+Object.values(catalog.products).find(p=>p.plannerId===id).price,0);$(e).text('$'+total.toLocaleString(en?'en-US':'es-CO')+' COP');});
 $('#experiences-grid > [data-category]').each((i,e)=>{const card=$(e);const id=(card.find('[onclick*="addToCart("]').first().attr('onclick')||'').match(/addToCart\(['"]([^'"]+)/)?.[1]||card.find('[data-product-id]').first().attr('data-product-id');const p=catalog.products[id];if(p)card.attr('data-price',p.price);});
 writeFileWithRetry(f,$.html());
}
