/* Build the first-paint navigation from the same renderer used in the browser. */
const fs=require('fs'),path=require('path'),vm=require('vm'),cheerio=require('cheerio');
const version='20260915d',catalog=require('../data/catalog.json');
const boatRoutes={es:'/renta-de-botes',en:'/en/private-boats',fr:'/fr/location-bateau',de:'/de/bootsmiete'};
const boatCopy={es:['Botes privados','Renta de botes privados en Cartagena','Un día en el mar, a tu ritmo y con tu grupo. Cuéntanos cuántas personas viajan, la fecha y el recorrido que tienen en mente.','Estamos preparando el catálogo de embarcaciones. Las fotos, capacidades, servicios y tarifas se publicarán cuando estén confirmados.','Tu grupo','Número de pasajeros y necesidades del grupo.','Tu recorrido','Bahía de Cartagena o salida a las islas: comparte tu idea.','Tu fecha','Horario, duración y presupuesto para orientar la selección.','Consultar un bote privado','Hola, me interesa un bote privado. Fecha: __. Personas: __. Recorrido: __.'],en:['Private boats','Private boat rentals in Cartagena','A day at sea with your own group and your preferred pace. Tell us your travel date, group size and the route you have in mind.','We are preparing the boat catalog. Photos, capacity, services and rates will be published once confirmed.','Your group','Number of passengers and any group requirements.','Your route','Cartagena Bay or the islands: tell us your plans.','Your date','Preferred schedule, duration and budget.','Ask about a private boat','Hello, I am interested in a private boat. Date: __. People: __. Route: __.'],fr:['Bateaux privés','Location de bateaux privés à Carthagène','Une journée en mer avec votre groupe, à votre rythme. Indiquez la date, le nombre de voyageurs et le parcours souhaité.','Nous préparons le catalogue des bateaux. Photos, capacités, prestations et tarifs seront publiés après confirmation.','Votre groupe','Nombre de passagers et besoins particuliers.','Votre parcours','Baie de Carthagène ou îles : partagez votre idée.','Votre date','Horaires, durée et budget souhaités.','Demander un bateau privé','Bonjour, je cherche un bateau privé. Date : __. Personnes : __. Parcours : __.'],de:['Private Boote','Private Boote in Cartagena mieten','Ein Tag auf dem Meer mit Ihrer eigenen Gruppe. Teilen Sie uns Reisedatum, Teilnehmerzahl und gewünschte Route mit.','Wir bereiten den Bootskatalog vor. Fotos, Kapazitäten, Leistungen und Preise werden nach Bestätigung veröffentlicht.','Ihre Gruppe','Teilnehmerzahl und besondere Anforderungen.','Ihre Route','Cartagena-Bucht oder Inseln: Beschreiben Sie Ihre Wünsche.','Ihr Termin','Gewünschte Uhrzeit, Dauer und Budget.','Privates Boot anfragen','Hallo, ich suche ein privates Boot. Datum: __. Personen: __. Route: __.']};
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
for(const l of Object.keys(boatRoutes)){
 const t=boatCopy[l],template=l==='es'?'about.html':l==='en'?'en/about.html':l==='fr'?'fr/a-propos.html':'de/ueber-uns.html';
 const $=cheerio.load(fs.readFileSync(template,'utf8'));$('body').html('<nav></nav><main class="boats-page" id="main-content"><div class="boat-intro"><h1>'+t[1]+'</h1><p>'+t[2]+'</p></div><div class="boat-facts">'+[4,6,8].map(i=>'<section><h2>'+t[i]+'</h2><p>'+t[i+1]+'</p></section>').join('')+'</div><p class="boats-status">'+t[3]+'</p><a class="btn-primary intl-button" href="https://wa.me/573163030589?text='+encodeURIComponent(t[11])+'">'+t[10]+'</a></main><footer></footer><script src="/js/site-refresh.js?v='+version+'" defer></script>');
 $('title').text(t[1]+' | Dunas & Olas');$('meta[name=description]').attr('content',t[2]);$('link[rel=canonical]').attr('href','https://dunasyolas.com'+boatRoutes[l]);$('meta[property="og:url"]').attr('content','https://dunasyolas.com'+boatRoutes[l]);$('meta[property="og:title"]').attr('content',t[1]);$('meta[property="og:description"]').attr('content',t[2]);$('script[type="application/ld+json"]').remove();$('link[rel=alternate]').remove();for(const [lang,r]of Object.entries(boatRoutes))$('head').append('<link rel="alternate" hreflang="'+lang+'" href="https://dunasyolas.com'+r+'">');
 if(l==='fr'||l==='de'){const original=cheerio.load(fs.readFileSync(template,'utf8'));$('nav').replaceWith(original('nav').first());$('footer').replaceWith(original('footer').first());$('.intl-language-list a,.intl-footer-links a[hreflang]').each((i,e)=>{const a=$(e);if(boatRoutes[a.attr('hreflang')])a.attr('href',boatRoutes[a.attr('hreflang')]);});}
 fs.writeFileSync(boatRoutes[l].slice(1)+'.html',$.html());
}
for(const l of ['es','en']){
 const file=l==='es'?'index.html':'en/index.html',$=cheerio.load(fs.readFileSync(file,'utf8')),en=l==='en';
 $('.site-search-shell>i,.site-search-submit').remove();$('#site-search').after('<button type="button" class="site-search-submit" aria-label="'+(en?'Search':'Buscar')+'"><i class="fas fa-search" aria-hidden="true"></i></button>').attr('aria-autocomplete','list');$('script[src*="site-search.js"]').attr('src','/js/site-search.js?v=20260915e');
 const sections=$('main>section');if(!$('#home-experiences').length){sections.eq(0).attr('id','home-trust');sections.eq(1).attr('id','home-nohemi');sections.eq(2).attr('id','home-experiences');}
 $('#home-trust').after($('#home-experiences'));$('.home-hero #hero-content>span').remove();$('.home-hero .animate-bounce').remove();
 const actions=$('.home-hero a').filter((i,e)=>/arma-tu-viaje/.test($(e).attr('href')||'')).parent();actions.addClass('hero-actions').html('<a class="hero-primary" href="'+(en?'/en':'')+'/experiences">'+(en?'Explore experiences':'Ver experiencias')+'</a><a class="hero-secondary" href="'+(en?'/en':'')+'/arma-tu-viaje">'+(en?'Plan my trip':'Armar mi viaje')+'</a>');
 const ids=['pasadia_cuatro_islas','citytour_roa','paratrike_5'],names=en?['Rosario Islands day trip','Cartagena city experience','Paratrike over the Caribbean']:['Pasadía Islas del Rosario','Cartagena histórica con ROA','Paratrike sobre el Caribe'];
 $('#home-experiences').html('<div class="home-picks-wrap"><h2>'+(en?'Choose your Cartagena experience':'Elige cómo vivir Cartagena')+'</h2><p>'+(en?'Compare starting prices and programs. We confirm the details with you before booking.':'Compara precios y programas. Confirmamos los detalles contigo antes de reservar.')+'</p><div class="home-picks">'+ids.map((id,i)=>{const p=catalog.products[id];return '<article><a href="'+(en?'/en':'')+p.route+'"><img src="'+p.image+'" alt="'+names[i]+'" width="1200" height="800" loading="lazy" decoding="async"></a><div><h3>'+names[i]+'</h3><p class="home-pick-price">'+(en?'From ':'Desde ')+'$'+p.price.toLocaleString('es-CO')+' COP <small>'+(en?'per person':'por persona')+'</small></p><a class="btn-primary" href="'+(en?'/en':'')+p.route+'">'+(en?'View experience':'Ver experiencia')+'</a></div></article>';}).join('')+'</div><a class="home-all" href="'+(en?'/en':'')+'/experiences">'+(en?'View all experiences →':'Ver todas las experiencias →')+'</a></div>');
 $('#home-private-boats').remove();const t=boatCopy[l];$('#home-nohemi').after('<section id="home-private-boats" class="private-boats-teaser"><div class="private-boats-layout"><div><h2>'+t[1]+'</h2><p>'+t[2]+'</p><a class="intl-button" href="'+boatRoutes[l]+'">'+(en?'Explore private boats':'Conoce la sección de botes')+'</a></div><img src="/images/cartagenasunset.webp" alt="'+(en?'Cartagena Bay at sunset':'Bahía de Cartagena al atardecer')+'" width="1400" height="933" loading="lazy" decoding="async"></div></section>');
 fs.writeFileSync(file,$.html());
}
const source=fs.readFileSync('js/site-refresh.js','utf8'),start=source.indexOf('  function initSiteNavigation() {')+'  function initSiteNavigation() {'.length,end=source.indexOf('    var menuButton = nav.querySelector');
if(start<30||end<start)throw new Error('Navigation renderer changed; update build boundary');
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>['node_modules','.git','.vercel','tmp'].includes(e.name)?[]:e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);}
let count=0;for(const file of walk('.').filter(f=>f.endsWith('.html'))){
 const $=cheerio.load(fs.readFileSync(file,'utf8')),l=($('html').attr('lang')||'es').slice(0,2);$('html').addClass('brand-refresh-active');
 $('meta[name="theme-color"]').attr('content','#08283e');$('link[href*="conversion.css"]').remove();$('head').append('<link rel="stylesheet" href="/css/conversion.css?v='+version+'">');
 if(!$('link[href*="brand-refresh.css"]').length)$('head').append('<link rel="stylesheet" href="/css/brand-refresh.css?v='+version+'">');
 $('link[href*="brand-refresh.css"]').attr('href','/css/brand-refresh.css?v='+version).attr('rel','stylesheet').removeAttr('onload');
 $('head').append($('link[href*="conversion.css"]'));
 $('script[src*="site-refresh.js"]').attr('src','/js/site-refresh.js?v='+version);
 if(l==='es'||l==='en'){
  const nav={innerHTML:'',className:''},canonical=$('link[rel=canonical]').attr('href')||'https://dunasyolas.com/',pathname=new URL(canonical).pathname;
  const document={documentElement:{lang:l},querySelector(selector){if(selector==='nav')return nav;const n=$(selector).first();if(!n.length)return null;return{href:n.attr('href'),setAttribute(k,v){n.attr(k,v);}};}};
  vm.runInNewContext('(function(){'+source.slice(start,end)+'})()',{document,window:{location:{pathname,href:canonical}},URL});
  $('#mobile-menu').remove();
  $('nav').first().replaceWith('<nav class="'+nav.className+'" data-static-nav="true">'+nav.innerHTML+'</nav>');
 }else{
  $('.intl-links,.intl-menu-list').each((i,e)=>{if(!$(e).find('a[data-boats]').length)$(e).append('<a data-boats href="'+boatRoutes[l]+'">'+boatCopy[l][0]+'</a>');});
 }
 $('.catalog-card div').filter((i,e)=>$(e).children('.add-to-cart-btn,.add-to-cart-btn-solid').length>0).addClass('catalog-actions');
 $('.catalog-actions>.whatsapp-info-btn').each((i,e)=>{$(e).attr('aria-label',l==='en'?'Ask about this experience on WhatsApp':'Consultar esta experiencia por WhatsApp').html('<i class="fab fa-whatsapp" aria-hidden="true"></i><span>WhatsApp</span>');});
 fs.writeFileSync(file,$.html().replace(/[ \t]+$/gm,''));count++;
}
console.log('Design and static navigation built: '+count+' pages.');
